version: '3.8'

services:
  redis:
    image: redis:latest
    command: "redis-server && redis-cli FLUSHALL"

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

  game:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PORT: 8080